### ISSUE TITLE
using the CopyPsProfile AND/OR CustomPsProfilePath errors

### ISSUE THREAD

**Issue by BanterBoy** [BanterBoy/Windows-Sandbox#14]
Start-WindowsSandbox -WindowsTerminal -VsCode -Git -Memory 8 -ReadWriteMappings @('C:\Temp\', 'C:\GitRepos\') -CopyPsProfile -CustomPsProfilePath "C:\GitRepos\ProfileFunctions\"os\ProfileFunctions\"

Start-WindowsSandbox: Cannot validate argument on parameter 'CustomPsProfilePath'. The supplied custom profile path does not exist.

Start-WindowsSandbox -WindowsTerminal -VsCode -Git -Memory 8 -ReadWriteMappings @('C:\Temp\', 'C:\GitRepos\') -CopyPsProfile

Copy-Item: C:\GitRepos\Windows-Sandbox\Start-WindowsSandbox.ps1:240
Line |
 240 |              Copy-Item -Path $CustomPsProfilePath -Destination $wsbSha …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\False' because it does not exist

**Comment by BanterBoy** [comment]
Issue happens on Windows 11 but was previously working on Windows 10

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by trossr32** [comment]
Ignore, spotted error

**Comment by trossr32** [comment]
@BanterBoy you're gonna kick yourself you didn't spot the error with this one 😄
